### ISSUE TITLE
Basic Schema

### ISSUE THREAD

**Issue by kuanwen-C** [TaiwanCodingShrimp/ECO#2]

**Comment by nush-cc** [comment]
>[!NOTE]
>[氣象局API](https://opendata.cwa.gov.tw/devManual/datalist)
>[政府資料開放平臺](https://data.gov.tw/)
>[Google Maps API](https://developers.google.com/maps/documentation/javascript/overview?hl=zh-tw)

# Schema

- user
	1. user id
	2. user account
- trip
	1. From (departure)
	2. to (destination)
	3. date
	4. user
	5. index (for each user to record trips)
- weather
	1. high (temperature)
	2. low (temperature)
	3. rainy
	4. location
- homestay 目前我以民宿為主
	1. name
	2. address
	3. location
- attractions
	1. name
	2. location
	3. feature
	4. cost
	5. homestay_name

# reference:
1. trip.user reference user.id
2. homestay.location reference weather.location
3. attractions.location reference weather.location
4. attractions.homestay_name reference homestay.name

# flow
1. 使用者輸入帳號，後臺存入trip中
2. 使用者輸入出發及終點，日期（用於判斷預報的提供與否）(後續可以增加花費等屬性)
3. 透過氣象局API找出會經過的路徑7天的天氣預報 （可能可以寫一個演算法平均一下）
4. 可以做一個選單讓使用者選擇要去的景點
	- 在使用者輸入起點跟終點後，後臺過濾會經過的景點出來供使用者選擇
5. 根據使用者選擇的景點，透過 google maps 與 homestay 算出路徑最短
	- ==有個問題是目前我只找到民宿列表，但沒有評價或是價錢之類的數據==
6. 最後再判斷天氣與路徑的關聯，若經過的路徑天氣不好則告知使用者並建議更換景點

**Comment by nush-cc** [comment]
briefly schema and flow, please confirm and give suggestions, but I think the database should be more complete, otherwise it will deviate from the theme of the project.

**Comment by ShanWei-Ch** [comment]
FYI
homestay average price : https://taiwanstay.net.tw/statistics-archive-list/hotel/225
attractions list : https://stat.taiwan.net.tw/scenicSpot

**Comment by kuanwen-C** [comment]
app:
account :user
planner:trip（main)
geo-info

**Comment by kuanwen-C** [comment]
this was old version of the project
